export const accessToken =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6ImRhaSIsImVtYWlsIjoiZGFpMkBnbWFpbC5jb20iLCJpYXQiOjE3MDc3NTEyMjgsImV4cCI6MTcwODM1NjAyOCwiYXVkIjoidXNlcnMiLCJpc3MiOiJsb2dpbiIsInN1YiI6IjIifQ.3KEekJqb3eEHHaMm_kUfufQ5An22obZRLr4pHuTLnuI';
